feat: add include and exclude glob options to product attestor
testifysec/go-witness pull request #41
Opened 2023-02-26 21:50 UTC by mikhailswift

This allows users to configure the product attestor to only include certain files from the product attestor as subjects to the attestation.

2023-02-26 22:09 UTC, kriscoleman submitted a review, later dismissed
seems like a nice way to add glob include/excludes, still learning this part of codebase.

2023-02-27 16:58 UTC, colek42 requested changes

2023-02-27 17:07 UTC, colek42 commented
sorry, I apparently cant read

2023-02-27 17:08 UTC, colek42 approved these changes

2023-02-27 17:10 UTC, merged