feat/add delegated api support
testifysec/go-witness pull request #5
Opened 2022-07-21 20:29 UTC by colek42

This adds support for SPIRE delegated API.  This allows withness to request certs on behalf of the workload it is running.

2022-07-21 20:33 UTC, mikhailswift requested changes
is there anyway to test this functionality?

2022-07-21 20:33 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +	fmt.Printf("#####: %s", socketPath)
remove fmt.Prints

2022-07-21 20:33 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +		os.Exit(1)
remove fmt.Print and don't call os.Exit from library code

2022-07-21 20:33 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +	s, err := ioutil.ReadFile(binPath)
prefer os.ReadFile, ioutil is deprecated

2022-07-21 20:33 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +		os.Exit(1)
same as above, remove print and don't call os exit from library code

2022-07-21 20:33 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +	fmt.Printf("### %s", svid.X509Svid)
remove

2022-07-21 20:33 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +		fmt.Printf("\n%s", cert.URIs[0])
remove

2022-07-21 20:34 UTC, mikhailswift commented
commit structure should be `feat: xxxx` for conventional commits and changelog generator to work appropriately

2022-07-21 20:39 UTC, colek42 commented
> is there anyway to test this functionality?

The SPIRE agent needs to be set up with delegated API to test it.  I have it working in scribe, but we should probably find a way to test SPIRE stuff in our open source.

2022-07-22 18:25 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +	s, err := ioutil.ReadFile(binPath)
In actuality we should probably be using os.Open and io.Copy instead of reading the entire file into memory.

2022-07-22 18:29 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +	svids := resp.X509Svids
svids isn't used outside of the line below this, so this can just be `svid := resp.X509Svids[0]`.

2022-07-22 18:30 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +	chain := svid.X509Svid.CertChain
similarly this is only used in the loop below, so can be `for _, cert := range svid.X509Svid.CertChain`

2022-07-22 18:30 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +	privateBytes := svid.X509SvidKey
And same here

2022-07-22 18:34 UTC, mikhailswift commented on signer/spiffe/spiffe.go
> +func DelgatedSigner(ctx context.Context, socketPath string, workloadPath string) (cryptoutil.Signer, error) {
we probably should be checking array lengths before accessing them in this function to prevent panics

2022-09-19 19:26 UTC, colek42 commented
I think this would make more sense as a "blocklist" of hashes we do not trust.

2022-09-21 16:10 UTC, mikhailswift commented
Not sure what you mean on the blocklist comment?

What's the status of this PR?

2023-10-26 18:16 UTC, closed without merging